# Generated by Django 3.1.6 on 2021-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notingApp', '0004_auto_20210927_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notingmodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
