# Generated by Django 3.1.6 on 2021-09-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notingApp', '0007_auto_20210927_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notingmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notingmodel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
