# Generated by Django 3.1.6 on 2021-09-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notingApp', '0009_auto_20210927_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notingmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
